.PHONY: test

SERVICE_NAME=my-service

deps:
	pip install -r requirements.txt && \
	pip install -r test_requiremnets.txt

run_local:
	echo "run $(SERVICE_NAME)"

test:
	echo "test $(SERVICE_NAME)"

test_integration:
	@echo "test integration $(SERVICE_NAME)"

clean:
	echo "optional clean"
